INSERT INTO authors (name) VALUES ('Stanisław Lem');
INSERT INTO books (author_id, title, year) VALUES (1, 'Solaris', 1962);
INSERT INTO books (author_id, title, year) VALUES (1, 'Fiasko', 1979);
INSERT INTO authors (name) VALUES ('Henry Miller');
INSERT INTO books (author_id, title, year) VALUES (2, 'Tropic of Cancer', 1934);
INSERT INTO books (author_id, title, year) VALUES (2, 'Tropic of Capricorn', 1950);
INSERT INTO books (author_id, title, year) VALUES (2, 'The smile at the foot of the ladder', 1948);
INSERT INTO authors (name) VALUES ('J.R.R. Tolkien');
INSERT INTO books (author_id, title, year) VALUES (3, 'The Hobbit', 1937);
INSERT INTO books (author_id, title, year) VALUES (3, 'The Lord of the Rings', 1950);
INSERT INTO authors (name) VALUES ('Fyodor Dostoyevsky');
INSERT INTO books (author_id, title, year) VALUES (4, 'Crime and punishment', 1884);
INSERT INTO books (author_id, title, year) VALUES (4, 'The Brothers Karamazov', 1880);
INSERT INTO books (author_id, title, year) VALUES (4, 'White Nights', 1848);
INSERT INTO authors (name) VALUES ('Gabriel Garcia Marquez');
INSERT INTO books (author_id, title, year) VALUES (5, 'Cien años de soledad', 1967);
INSERT INTO books (author_id, title, year) VALUES (5, 'El amor en los tiempos del cólera', 1985);
INSERT INTO authors (name) VALUES ('Virginia Woolf');
INSERT INTO books (author_id, title, year) VALUES (6, 'Mrs Dalloway', 1925);
INSERT INTO books (author_id, title, year) VALUES (6, 'To The Lighthouse', 1927);
INSERT INTO authors (name) VALUES ('Roberto Bolano');
INSERT INTO books (author_id, title, year) VALUES (7, 'Los detectives salvajes', 1985);
INSERT INTO books (author_id, title, year) VALUES (7, 'Nocturno de Chile', 2000);